keyboard.bindings = [
    { key = "Left", mods = "Alt", chars = "\u001bb" },
    { key = "Right", mods = "Alt", chars = "\u001bf" },
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    { key = "Right", mods = "Command", chars = "\u001bOF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
]
